### PR TITLE
AngularJS SPA Todo sample

### PR DESCRIPTION
**Pull request by biste5**
A simple example which uses AMS JavaScript SDK, AngularJS to perform simple operations on standard TodoItem table.
Login with different providers is also implemented

### CODE REVIEW

**Comment by biste5** [comment]
is it going to be merged? 
Is there something incorrect or not clear with the sample?

**Comment by lindydonna** [comment]
Sorry for the delay!  We were waiting for a code review from @danderson00. I'll ping him again. :)

**Comment by danderson00** [comment]
Generally looks good. There seem to be some presentation issues when shown in IE11 with document mode set to 7 (the default). Interestingly, I only noticed this when hitting the site using a domain or machine name (not localhost), I suspect this is to do with a difference in how IE treats localhost addresses.

**Comment by biste5** [comment]
Probably you're right, I'm not an expert in bootstrap and design in general (I understand issue is related to that). Also in the login page, some images are included just to show the functionality. I'm not assuming it will scale ad look properly with all browsers and devices... Aim of the sample is not to provide a perfect bootstrap template, but instead to show the functionalities and the communication with AMS..

**Pull request merged**
